---

- name: google chrome installation
  package: name=google-chrome-stable state=present

- name: chromium installation
  package: name={{ item }} state=present
  with_items: "{{ chromium_packages | distro(vars) }}"
