---

- name: google chrome repository keys
  apt_key: id=4CCA1EAF950CEE4AB83976DCA040830F7FAC5991 keyserver=keys.gnupg.net

- name: google chrome repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
